---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ing
  labels:
    app: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
        - path:  {{ .Values.app.urlPath }}
          backend:
            serviceName:  {{ .Release.Name }}-svc
            servicePort:  {{ .Values.app.servicePort }}


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.flower.name }}-ing
  labels:
    app: {{ .Values.flower.name }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.flower.ingressClass | quote }}
    ingress.kubernetes.io/rewrite-target: {{ .Values.flower.rewriteTarget }}
spec:
  rules:
  - http:
      paths:
        - path: {{ .Values.flower.prefixPath }}
          backend:
            serviceName: {{ .Values.flower.name }}-svc
            servicePort: {{ .Values.flower.servicePort }}
