global:
  image: minh5/airflow
  imageTag: 0.0.5
  pullPolicy: Always
  restartPolicy: Always
  dagStart: false
  concurrency: 24

app:
  tier: web
  replicas: 1
  servicePort: 8080
  containerPort: 8080
  urlPath: /airflow

worker:
  tier: worker
  updateStrategy: RollingUpdate
  podPolicy: Parallel
  replicas: 1
  terminationPeriod: 30
  containerPort: 8793
  servicePort: 8793


scheduler:
  tier: scheduler
  replicas: 1
  restartPolicy: Always

flower:
  name: flower
  containerPort: 5555
  servicePort: 5555
  ingressClass: nginx
  rewriteTarget: /
  prefixPath: /flower
  
persistence:
  enabled: true
  logs:
    name: logs-storage
    storageClass: generic
    accessMode: ReadWriteOnce
    requestSize: 1Gi
    size: 8Gi
    path: /home/airflow/logs
  dags:
    name: dags-storage
    storageClass: generic
    accessMode: ReadWriteOnce
    requestSize: 1Gi
    size: 2Gi
    path: /home/airflow/dags

extra:
  airflowConfigs: {}
  envs:
  pip:
  secrets:

initFile: |-
  airflow initdb
  bash /tmp/config/config.sh
  bash /usr/local/bin/airflow-init $@
