{{- if .Values.persistence.enabled }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.persistence.dags.name }}
  labels:
    type: {{ .Values.persistence.dags.storageClass }}
spec:
  capacity:
    storage: {{ .Values.persistence.dags.size }}
  accessModes:
    - {{ .Values.persistence.dags.accessMode }}
  hostPath:
    path: {{ default "usr/local/airflow/dags" .Values.persistence.dags.path | quote }}


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.dags.name }}
spec:
  accessModes:
    - {{ .Values.persistence.dags.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.dags.requestSize }}


---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.persistence.logs.name }}
  labels:
    type: {{ .Values.persistence.logs.storageClass }}
spec:
  capacity:
    storage: {{ .Values.persistence.logs.size }}
  accessModes:
    - {{ .Values.persistence.logs.accessMode }}
  hostPath:
    path: {{ default "usr/local/airflow/logs" .Values.persistence.logs.path | quote }}


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.logs.name }}
spec:
  accessModes:
    - {{ .Values.persistence.logs.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.requestSize }}
{{- end }}
