---
apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ .Values.scheduler.tier }}
spec:
  replicas: {{ .Values.scheduler.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        tier: {{ .Values.scheduler.tier }}
    spec:
      restartPolicy: {{ .Values.scheduler.restartPolicy }}
      containers:
      - name: {{ .Release.Name }}-{{ .Values.scheduler.tier }}
        image: {{ .Values.global.image}}:{{ .Values.global.imageTag }}
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        command:
          - "/bin/bash"
          - "/tmp/config/init.sh"
          - "-scheduler"
{{- include "common_deployment" . -}}