---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: {{ .Release.Name }}-app
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.app.containerPort }}
      targetPort: {{ .Values.app.servicePort }}
      protocol: TCP
      name: {{ .Release.Name }}


---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.flower.name }}-svc
  labels:
    app: {{ .Values.flower.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.flower.name }}
  ports:
    - port: {{ .Values.flower.containerPort }}
      targetPort: {{ .Values.flower.servicePort }}
      protocol: TCP
      name: {{ .Values.flower.name }}


---
# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.worker.tier }}-svc
spec:
  ports:
    - name: {{ .Values.worker.tier }}-log
      port: {{ .Values.worker.servicePort }}
  clusterIP: None
  selector:
    app: {{ .Release.Name }}

